spring.application.name=fitcheck
logging.level.root=INFO
logging.level.com.fitcheck=DEBUG

spring.config.import=optional:file:.env.local[.properties]

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE}&sslrootcert=${DB_SSL_CERT_PATH:}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate